### ISSUE TITLE
Highcharts on Mobile

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#136]
On mobile, the catch highchart columns are running into one another. The source information also runs off the page, so we'll want to add a line break to it to ensure that doesn't happen.

<img width="368" alt="screen shot 2019-01-04 at 7 49 19 am" src="https://user-images.githubusercontent.com/1896496/50688843-4f19b600-0ff5-11e9-9b20-aa4f806fc4ab.png">

**Comment by aleesteele** [comment]
Just a note. Currently working on this at https://github.com/CSIS-iLab/ocean/tree/fix/highchart (`fix/highchart`)
