### ISSUE TITLE
Component: Authors List

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#15]
Display a list of author names

- [x] Names should link to the author's page
- [x] List should be comma separate if more than 3 authors (eg. Jane Dot, John Doe, and Harry Potter)
- [x] Ultimate & penultimate names should be separate by "and" (eg. Jane Dot and John Doe)

**Comment by aleesteele** [comment]
Note: this is being added to the branch `feature/publish-date` because of it's similar styles to the authors block and published date.
