### ISSUE TITLE
Bugs and Other Notes 

### ISSUE THREAD

**Issue by aleesteele** [CSIS-iLab/ocean#163]
Bugs: Oceans Website
Note: Some of the bugs I'm seeing might be because I have a different height/width screen ratio.

**Bugs**
- [x] I'm not sure if this is on purpose, but the spotlight navigation doesn't reach the bottom of the screen on my computer. (See screenshot below) **L**
  - **It should reach the bottom, please** -T
- [x] The Spotlight navigation also appears to be a little buggy. Clicking on the appropriate section sometime doesn't show the appropriate dash (–) next to it. Also, the title of the section appears at various places on the screen when this is done. **L**
  - **I haven't seen the dash thing, but we should look at the anchor/scroll location. Right now the title isn't visible on the screen once the page is done scrolling.** -T
![screen shot 2019-01-03 at 9 40 43 am](https://user-images.githubusercontent.com/18509789/50712121-4e594200-103e-11e9-81f9-b4111c925b41.png)
- [x] Not sure if this will be added in later, but the 'Mailing list' link doesn't go anywhere. **J* 
- [x] ~You can still scroll through the content while the mobile Spotlight menu is open on mobile/smaller screens. The red progress bar loads.~ **Not a bug**
- [x] Home page: PRESERVE doesn't show up on mobile screens (checked on iPhone) **J**
![screen shot 2019-01-04 at 4 44 20 pm](https://user-images.githubusercontent.com/18509789/50712582-09360f80-1040-11e9-8798-6c412df1a092.png)
- [x] On the spotlight, changing the single image (ie the AIS signals map) to 'small' actually increases its size. **L**
  - **There isn't a 'small' size for single images that aren't floated, but I was having a similar problem with the 'medium' size. Please fix!** -T
![screen shot 2019-01-07 at 8 32 20 am](https://user-images.githubusercontent.com/18509789/50770907-e6ca0f00-1256-11e9-8e9d-b4fa48583d5c.png)

**Other**
- [x] ~I'm not sure if this is on purpose, but there's a bit space between the SOS description and the copyright info.~ **I noted this in my design issue** -T
![screen shot 2019-01-04 at 9 55 39 am](https://user-images.githubusercontent.com/18509789/50712190-937d7400-103e-11e9-9b11-bf76a14ff934.png)
- [x] ~On mobile, Greg’s bio stays aligned to the left after being previously centered. Screenshot below. Not sure if on purpose.~ **That's on purpose. It's difficult to read longer paragraphs that are center-aligned.** -T
![screen shot 2019-01-04 at 4 38 59 pm](https://user-images.githubusercontent.com/18509789/50712398-5cf42900-103f-11e9-80b5-134af294ba7b.png)
- [x] On mobile, the animated scroll gets kinda wonky for the waves (you can pause scrolling mid-way between the wave and the sky. **J**
- [x] ~On the homepage, the main video plays on mobile screens within the design elements. Not sure if it should auto-expand to full-screen on mobile devices.~ **Not a bug**

**Comment by jnschrag** [comment]
@aleesteele I've added comments to a few of these that are not bugs. Can you please add clarifying information to these:

> Changing the GIF size to 'small' actually makes it large.
What GIF?

> About page: right column isn’t white/no pseudo element. Not sure if on purpose.
Are you referring to the dark background on the right side? If so, that is intentionally. It isn't supposed to be white all the way across the page.

> When the video plays on mobile screens, not sure if it should auto-expand to full-screen.
What video?

**Comment by aleesteele** [comment]
@jnschrag I went through the notes and edited them accordingly! By video, I had meant the one on the homepage, and I had made a mistake with the GIF note. I actually meant the AIG signals single image, and added a screenshot of what I meant to the list.

**Comment by aleesteele** [comment]
More notes w/ screenshots!

- [ ] Going off of what Tucker said about how Greg's bio is staying aligned to the left b/c it's a block of text, should the bios be changed?
![screen shot 2019-01-07 at 1 24 40 pm](https://user-images.githubusercontent.com/18509789/50785751-9b782680-127f-11e9-8900-7988ea26b335.png)
- [ ] Not sure about arrow placements on mobile of these, figured I'd add them to the list. Also the photos are different sizes, though they default to the same crop.
![image-1](https://user-images.githubusercontent.com/18509789/50785951-23f6c700-1280-11e9-8b64-f3e1319fa057.jpeg)
![image-2](https://user-images.githubusercontent.com/18509789/50785952-23f6c700-1280-11e9-80a1-fefa683bf354.jpeg)
- [ ] There's a big space between the published date and the lede for this post, because it includes a photo I think. Not sure if this is a design spec or error, but you can see it on Greg's author page. None of the commentaries have photos so this isn't shown elsewhere.
![screen shot 2019-01-07 at 1 32 20 pm](https://user-images.githubusercontent.com/18509789/50786232-ecd4e580-1280-11e9-9fd1-af2cfeddad21.png)

**Comment by aleesteele** [comment]
Notes for Internet Explorer & Edge
I **bolded** the ones that seemed most important

*Internet Explorer*
- [ ] **The search function/search bar doesn't appear when clicked.**
- [ ] Neither PROTECT nor PRESERVE show up on internet Explorer on the Homepage
- [ ] **Pagination does not appear on archive pages**

**Comment by aleesteele** [comment]
### Other Notes
Homepage seemed a little funky for both EDGE & Chrome on a windows computers.
![edge-homepage](https://user-images.githubusercontent.com/18509789/50835873-d46ad680-1325-11e9-833f-9436a8032bed.PNG)
