### ISSUE TITLE
Arctic Spotlight

### ISSUE THREAD

**Issue by aleesteele** [CSIS-iLab/ocean#226]
### Implementation
- [x] Basic text 
  - [x] Links
  - [x] Footnotes
- [x] Excerpt
- [x] Components
    - [x] Tooltip (2/2)
    - [x] Blockquote (1/1)
    - [x] Explainer (1/1)
    - [x] Statistic (1/1)
- [x] Arctic Map Viz
    - [x] Map Assets (#?)
    - [x] Viz
- [x] Hero Header
- [x] Assets
    - [x] Static image: MPAs map
    - [x] Static image: Map w/ territorial waters, EEZs, & ABNJ
    - [ ] Photos(?)
- [x] Further Reading
- [x] Methodology
- [x] Tags
- [x] Contributors
    - [x] Development and Design
- [x] Preview Image and Source (for post blocks)
- [x] Related Spotlights
- [x] Related Commentary

## Additional Items
- [x] On the scrollytelling dropdown, the `<option>` text should be black (but the selector text should stay white)
- [x] Remove the illustration credit
- [x] Adjust the footnotes so only the first 3 show
- [x] Add text to the bottom of the scrollytelling container for source credit. Use placeholder text for now.

**Comment by tuckabelle** [comment]
## Photos/Graphics
Note that there aren't captions for the National Geographic photos yet
- [ ] Remove the image at the top of the "Charting the Future..." section
- [ ] Move the EEZs graphic to top of the section
- [ ] Optimize photos I sent you and add them to Cloudinary:
Add photos as follows
- [ ] Go to the MPA map graphic. Create a gallery component and add the map graphic as well as FJ3_4073, FJ3_1460, FJ2_0232LO, FJ1_6097
- [ ] Add noaa_unmanned_aircraft_recovery to the top of the "Governing an Unchartered Ocean." Make it a medium size and float right. The caption should read: "The Puma operator aboard the U.S. Coast Guard zodiak recovers the small unmanned aircraft after demonstrating its capabilities for detecting oil from the air during Arctic Shield 2013." source:"NOAA"


#### Photo captions
For the MPA map:
- [ ] update the caption: "Marine Protected Areas in the Arctic as defined by the Arctic Council’s working group for the Protection of the Marine Environment" source: "Based on PAME's 2017 [Indicator Report](https://pame.is/images/03_Projects/MPA/Indicator/Indicator_Report_on_Protected_Areas_.pdf)"

EEZ graphic:
- [ ] update the source:"Based on EEZ boundaries from the [Arctic Portal](https://portlets.arcticportal.org/governance-of-the-arctic/13-the-arctic-governance)"


## Footnotes
- [ ]  Add the following footnote after "...of marine protected areas (MPAs)..." (so it should be "..network of marine protected areas (MPAs)[^6] across the.."):
PAME has defined Arctic MPAs using the IUCNs general definition of an MPA as “A clearly defined geographical space recognized, dedicated, and managed, through legal or other effective means, to achieve the long-term conservation of nature with associated ecosystem services and cultural values”.  This definition has been [criticized for being overly broad]( https://reader.elsevier.com/reader/sd/pii/S0308597X17307686?token=2D6F947C07587777F1F5B07C7C72BCC2A769079659FDBD992D5314F6ABB2D1E82ABDE2EBBF20BCC7999CD4F1F2894709) as it allows for the inclusion of special management and use areas for fisheries or other resources and should not be construed to represent only areas that are fully protected.  This is the case for most of the U.S. waters included in the PAME estimates which represent an array of zones with varying restrictions on fishing, navigation, or other resource use but typically do not restrict all commercial use.  A range of management approaches, including both fully conserved areas and special management zones, are necessary to support sustainable use and development.  However, [only fully protected areas](https://www.pewtrusts.org/-/media/assets/2018/02/recommendations-to-iucn-on-implementing-mpa-categories-for-printing.pdf) effectively conserve biodiversity and provide the most direct benefits to ecosystem resilience in the face of climate change

## Statistics
Find where the following quotes are and add the following statistic components around their location:
- [ ] "Around 21,000 species inhabit the Arctic Ocean, including 5,000 animal species."
- [ ] "An estimated 11.4 percent of the Arctic is currently under protected status."

## Misc. Design
- [ ] change the overall spotlight accent color to #90BEED
- [ ] reduce the number of footnotes visible before the "Read More" expander to 3

**Comment by dlousa92** [comment]
### Per Review on April 4th

Here are some bugs we found yesterday, as well as changes suggested by Dr. Saumweber

### Bugs

- [ ] The header for the Governing an Uncharted Ocean section is currently being hidden behind the scrollytelling piece. We fixed it temporarily by adding an element style but didn't look into a more permanent solution.

### Changes

- [ ] Add more whitespace & change gradient between the intro section and the scrollytelling piece to focus more on text.

- [ ] Change overall Blue to be a little brighter.

- [ ] Yellow or Red Hatch for the EEZ graphic. highlighting the center portion.

- [ ] Reorder content to talk about the Treaty first, and then talk about ABNJs, reposition the EEZ graphic to be below the paragraph that ends with "...and tens of thousands of ecologically critical microbes.".
