### ISSUE TITLE
Tina Migration Conversation

### ISSUE THREAD

**Issue by tfsomrat** [CSIS-iLab/ocean#270]
Hey, I hope you are doing well. You gave me access to migrate your site from Forestry to Tina. However, I can’t have access to push in your repositories
It would be great if you can provide me the access

**Comment by mariel-delagarza** [comment]
Hi there -- We've updated the permissions for you and @tfsojon to `write` on all 6 repos so you should be good to go now, but let us know if you have any problems.

**Comment by tfsomrat** [comment]
Hey @mariel-delagarza, thanks for giving me the `write` permission. I have created a new branch [tina-migration](https://github.com/CSIS-iLab/ocean/tree/tina-migration) and pushed the tina configuration there. all you need to do is create a new project in Tina, and set the `clientId` and `token`. you can check it on your local machine without `clientId` and `token`.

**Comment by tfsomrat** [comment]
Please let me know if you have any queries. thanks
