### ISSUE TITLE
Content: Commentaries

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#33]
Add initial commentaries content
- [x] Commentaries
- [x] Authors
- [x] Keywords

**Comment by aleesteele** [comment]
These were implemented on Forestry. Both SOS commentaries are now on the website.
Added: commentary text, keywords, and authors.

A few questions for when you all have time:
1. Should I use the excerpt or first few sentences/etc. for the lede? The excerpt might work as well, but there wasn't anything specifically noted on either the google doc or excel sheet about it.
2. On both the google sheet & the author docs, using title vs byline seemed a bit unclear. Monica noted that her title was 'Senior Associate (non-resident) at CSIS' for her title and 'Founder and Publisher of Our Daily Planet' for her byline. For Dan Myers and Carol, they were only noted with a title, so I used it for both fields.
3. Should there be a photo field in the forestry front matter for the authors? (commented on #7 about this, just in case). There were photos in the google folder, but I didn't see anything on Zeplin or the front matter notes for it.

**Comment by jnschrag** [comment]
1. No, Tucker and I will write the ledes once we get the final copy. Thanks for flagging it though! For now, please put placeholder/latin text so we remember to update it.
2. Tucker and I will update the author bylines as well.
3. No, authors do not need a photo. We had originally given them the opportunity (hence their inclusion in the Drive folder), but ultimately we decided to remove them from the design.
