### ISSUE TITLE
Collection: Posts

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#5]
## Set up front matter templates in Forestry
  - [x] Title
  - [x] Date
  - [x] Excerpt
  - [x] Authors ("sortable list", pull from `authors` collection)
  - [x] Keywords ("sortable list", pull from `keywords` data file)
  - [x] Further Reading (textarea, WYSIWYG editor)
  - [x] Related Content ("sortable list", pull from `posts` and `spotlights` collections)
  - [x] Image
  - [x] Image Caption
  - [x] Image Source
  - [x] Is Featured?

**Comment by leezaweb** [comment]
@jnschrag  
For "Related Content" on Oceans, I didn't have any luck making a sortable list that pulls from both posts and spotlights collections. The select for this doesn't allow multiple selections. There is an "All" option. Should I break this out into "related posts" and "related spotlights"?

**Comment by jnschrag** [comment]
> @jnschrag
> For "Related Content" on Oceans, I didn't have any luck making a sortable list that pulls from both posts and spotlights collections. The select for this doesn't allow multiple selections. There is an "All" option. Should I break this out into "related posts" and "related spotlights"?

Let's go with two fields like you suggested. One for related posts and one for related spotlights. Good catch!
