### ISSUE TITLE
Spotlights Component Structure

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/ocean#66]
Set up the structure for Spotlight components, including the helper classes to float components to left & right, wide, and full width.

- [x] Left/Right Helpers
- [x] Float Small/Large
- [x] Large
- [x] Max
- [x] Full Width
- [x] Example with Accent color

**Comment by aleesteele** [comment]
A couple of questions about setting up the styles. The document & statistics components are ready to be PR'd, but I wanted to ask a couple things about styles.

- The smaller spotlight components have a couple of things that seem reusable in terms of text styles. Should these be turned into placeholders that can be extended into the various elements of each spotlight? Right now, I placed these more general styles at the top of the sass file, for example: https://github.com/CSIS-iLab/ocean/pull/74/files#diff-ceae7fbba86d43335d7e1fea39e135a6

For example, if `spotlight-component__label` style has multiple uses across various spotlight components, should the above be used as a class on the element, versus the specific use case, like `statistic-label` or `statistic__label`?

- The styles for spotlight-components are currently in a `spotlights-components` file in the `spotlights` sass folder across all my PR's. Not sure if it's either in the right location.

- @leezaweb and I talked about this a bit, but I'm following her lead on putting all of the spotlight components in the includes folder. We weren't sure if they were supposed to be in the `_spotlights` folder.

**Comment by jnschrag** [comment]
- I like the way you've implemented it in the example by creating reusable classes that can be assigned to various components (eg. `spotlight-component__label` is better than `statistic-label`).
- Putting all of the styles in a `spotlights-components` file is correct for the smaller items that don't have a lot of extra styles involved. Larger components like the explainer, images, data viz, etc. will have their own folders.
- Yes, please put the includes in the `_includes` folder.
